services:
  postgres:
    image: postgres:17
    restart: always

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - rift-postgres-data:/var/lib/postgresql/data

    networks:
      - rift-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    restart: always

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - rift-redis-data:/data

    networks:
      - rift-network

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: .

      dockerfile: Dockerfile


    restart: always

    depends_on:
      postgres:
        condition:
          service_healthy

      redis:
        condition:
          service_healthy

    # ports:
    #   - "8080:8080"

    env_file:
      - .env.development

    environment:
      APP_ENV: development

      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DOCKER_ENV: "true"

    networks:
      - rift-network

  nginx:
    image: nginx:alpine

    restart: always

    depends_on:
      - backend

    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - rift-network


volumes:
  rift-postgres-data:
  rift-redis-data:


networks:
  rift-network: