ALTER TABLE refresh_tokens
ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ,

ADD COLUMN IF NOT EXISTS replaced_by_token TEXT,

ADD COLUMN IF NOT EXISTS user_agent TEXT,

ADD COLUMN IF NOT EXISTS ip_address TEXT;