// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec
INSERT INTO email_verification_tokens (
    user_id,
    token_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE
FROM email_verification_tokens
WHERE
    id = $1
    AND user_id = $2
`

type DeleteEmailVerificationTokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, arg DeleteEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, arg.ID, arg.UserID)
	return err
}

const deleteEmailVerificationTokensForUser = `-- name: DeleteEmailVerificationTokensForUser :exec
DELETE
FROM email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensForUser, userID)
	return err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE
FROM email_verification_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	return err
}

const getValidEmailVerificationToken = `-- name: GetValidEmailVerificationToken :one
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    created_at
FROM email_verification_tokens
WHERE
    token_hash = $1
    AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetValidEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getValidEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const isUserEmailVerified = `-- name: IsUserEmailVerified :one
SELECT email_verified
FROM users
WHERE id = $1
`

func (q *Queries) IsUserEmailVerified(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEmailVerified, id)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET
    email_verified = TRUE,
    updated_at = NOW()
WHERE
    id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
