// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_analytics.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLinkAnalytics = `-- name: CreateLinkAnalytics :exec
INSERT INTO link_analytics (
	link_id,
	referrer,
	country,
	city,
	browser,
	os,
	device,
	ip_address,
	utm_source,
	utm_medium,
	utm_campaign,
	utm_term,
	utm_content,
    is_bot
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
    $14
)
`

type CreateLinkAnalyticsParams struct {
	LinkID      pgtype.UUID
	Referrer    pgtype.Text
	Country     pgtype.Text
	City        pgtype.Text
	Browser     pgtype.Text
	Os          pgtype.Text
	Device      pgtype.Text
	IpAddress   *netip.Addr
	UtmSource   pgtype.Text
	UtmMedium   pgtype.Text
	UtmCampaign pgtype.Text
	UtmTerm     pgtype.Text
	UtmContent  pgtype.Text
	IsBot       bool
}

func (q *Queries) CreateLinkAnalytics(ctx context.Context, arg CreateLinkAnalyticsParams) error {
	_, err := q.db.Exec(ctx, createLinkAnalytics,
		arg.LinkID,
		arg.Referrer,
		arg.Country,
		arg.City,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.IpAddress,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.IsBot,
	)
	return err
}

const getAverageClicksPerVisitor = `-- name: GetAverageClicksPerVisitor :one
SELECT
    COALESCE(
        ROUND(
            COUNT(*)::NUMERIC /
            NULLIF(
                COUNT(DISTINCT ip_address),
                0
            ),
            2
        ),
        0
    ) AS average
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
`

type GetAverageClicksPerVisitorParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

func (q *Queries) GetAverageClicksPerVisitor(ctx context.Context, arg GetAverageClicksPerVisitorParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAverageClicksPerVisitor, arg.LinkID, arg.Column2)
	var average interface{}
	err := row.Scan(&average)
	return average, err
}

const getClicksInRange = `-- name: GetClicksInRange :one
SELECT
    COUNT(*)::BIGINT AS clicks
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND clicked_at >= $2
AND clicked_at < $3
`

type GetClicksInRangeParams struct {
	LinkID    pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

func (q *Queries) GetClicksInRange(ctx context.Context, arg GetClicksInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getClicksInRange, arg.LinkID, arg.StartTime, arg.EndTime)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}

const getClicksTimeline = `-- name: GetClicksTimeline :many
SELECT
    DATE(clicked_at)
        AS day,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY day
ORDER BY day ASC
`

type GetClicksTimelineParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetClicksTimelineRow struct {
	Day    pgtype.Date
	Clicks int64
}

func (q *Queries) GetClicksTimeline(ctx context.Context, arg GetClicksTimelineParams) ([]GetClicksTimelineRow, error) {
	rows, err := q.db.Query(ctx, getClicksTimeline, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClicksTimelineRow
	for rows.Next() {
		var i GetClicksTimelineRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHourlyClicks = `-- name: GetHourlyClicks :many
SELECT
    EXTRACT(HOUR FROM clicked_at)::INT AS hour,
    COUNT(*)::BIGINT AS clicks
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY hour
ORDER BY hour ASC
`

type GetHourlyClicksParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetHourlyClicksRow struct {
	Hour   int32
	Clicks int64
}

func (q *Queries) GetHourlyClicks(ctx context.Context, arg GetHourlyClicksParams) ([]GetHourlyClicksRow, error) {
	rows, err := q.db.Query(ctx, getHourlyClicks, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHourlyClicksRow
	for rows.Next() {
		var i GetHourlyClicksRow
		if err := rows.Scan(&i.Hour, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkAnalyticsOverview = `-- name: GetLinkAnalyticsOverview :one
SELECT
    COUNT(*)::BIGINT
        AS total_clicks,

    COUNT(*) FILTER (
        WHERE clicked_at >= NOW() - INTERVAL '24 hours'
    )::BIGINT
        AS clicks_today,

    COUNT(DISTINCT ip_address)::BIGINT
        AS unique_visitors
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
`

type GetLinkAnalyticsOverviewParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetLinkAnalyticsOverviewRow struct {
	TotalClicks    int64
	ClicksToday    int64
	UniqueVisitors int64
}

func (q *Queries) GetLinkAnalyticsOverview(ctx context.Context, arg GetLinkAnalyticsOverviewParams) (GetLinkAnalyticsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getLinkAnalyticsOverview, arg.LinkID, arg.Column2)
	var i GetLinkAnalyticsOverviewRow
	err := row.Scan(&i.TotalClicks, &i.ClicksToday, &i.UniqueVisitors)
	return i, err
}

const getRecentClicks = `-- name: GetRecentClicks :many






SELECT
    clicked_at,
    referrer,
    country,
    city,
    browser,
    os,
    device
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
ORDER BY clicked_at DESC
LIMIT 50
`

type GetRecentClicksParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetRecentClicksRow struct {
	ClickedAt pgtype.Timestamptz
	Referrer  pgtype.Text
	Country   pgtype.Text
	City      pgtype.Text
	Browser   pgtype.Text
	Os        pgtype.Text
	Device    pgtype.Text
}

// -- name: GetTotalClicks :one
// SELECT COUNT(*)
// FROM link_analytics
// WHERE link_id = $1;
// -- name: GetClicksByDay :many
// SELECT
//
//	DATE(clicked_at) AS day,
//	COUNT(*) AS clicks
//
// FROM link_analytics
// WHERE link_id = $1
// AND clicked_at >= NOW() - INTERVAL '30 days'
// GROUP BY day
// ORDER BY day ASC;
// -- name: GetCountryBreakdown :many
// SELECT
//
//	COALESCE(country, 'unknown') AS country,
//	COUNT(*) AS clicks
//
// FROM link_analytics
// WHERE link_id = $1
// GROUP BY country
// ORDER BY clicks DESC
// LIMIT 10;
// -- name: GetBrowserBreakdown :many
// SELECT
//
//	COALESCE(browser, 'unknown') AS browser,
//	COUNT(*) AS clicks
//
// FROM link_analytics
// WHERE link_id = $1
// GROUP BY browser
// ORDER BY clicks DESC;
// -- name: GetOSBreakdown :many
// SELECT
//
//	COALESCE(os, 'unknown') AS os,
//	COUNT(*) AS clicks
//
// FROM link_analytics
// WHERE link_id = $1
// GROUP BY os
// ORDER BY clicks DESC;
// -- name: GetDeviceBreakdown :many
// SELECT
//
//	COALESCE(device, 'unknown') AS device,
//	COUNT(*) AS clicks
//
// FROM link_analytics
// WHERE link_id = $1
// GROUP BY device
// ORDER BY clicks DESC;
func (q *Queries) GetRecentClicks(ctx context.Context, arg GetRecentClicksParams) ([]GetRecentClicksRow, error) {
	rows, err := q.db.Query(ctx, getRecentClicks, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentClicksRow
	for rows.Next() {
		var i GetRecentClicksRow
		if err := rows.Scan(
			&i.ClickedAt,
			&i.Referrer,
			&i.Country,
			&i.City,
			&i.Browser,
			&i.Os,
			&i.Device,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepeatVisitors = `-- name: GetRepeatVisitors :one
SELECT
    COUNT(*)::BIGINT AS repeat_visitors
FROM (
    SELECT ip_address
    FROM link_analytics
    WHERE link_id = $1
    AND is_bot = FALSE
    AND (
        $2::timestamptz IS NULL
        OR clicked_at >= $2
    )
    GROUP BY ip_address
    HAVING COUNT(*) > 1
) repeated
`

type GetRepeatVisitorsParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

func (q *Queries) GetRepeatVisitors(ctx context.Context, arg GetRepeatVisitorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRepeatVisitors, arg.LinkID, arg.Column2)
	var repeat_visitors int64
	err := row.Scan(&repeat_visitors)
	return repeat_visitors, err
}

const getTopBrowsers = `-- name: GetTopBrowsers :many
SELECT
    browser,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY browser
ORDER BY clicks DESC
LIMIT 10
`

type GetTopBrowsersParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopBrowsersRow struct {
	Browser pgtype.Text
	Clicks  int64
}

func (q *Queries) GetTopBrowsers(ctx context.Context, arg GetTopBrowsersParams) ([]GetTopBrowsersRow, error) {
	rows, err := q.db.Query(ctx, getTopBrowsers, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopBrowsersRow
	for rows.Next() {
		var i GetTopBrowsersRow
		if err := rows.Scan(&i.Browser, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCampaigns = `-- name: GetTopCampaigns :many
SELECT
    COALESCE(
        NULLIF(
            utm_campaign,
            ''
        ),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopCampaignsParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopCampaignsRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopCampaigns(ctx context.Context, arg GetTopCampaignsParams) ([]GetTopCampaignsRow, error) {
	rows, err := q.db.Query(ctx, getTopCampaigns, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCampaignsRow
	for rows.Next() {
		var i GetTopCampaignsRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCities = `-- name: GetTopCities :many
SELECT
    COALESCE(
        NULLIF(city, ''),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopCitiesParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopCitiesRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopCities(ctx context.Context, arg GetTopCitiesParams) ([]GetTopCitiesRow, error) {
	rows, err := q.db.Query(ctx, getTopCities, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCitiesRow
	for rows.Next() {
		var i GetTopCitiesRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopContent = `-- name: GetTopContent :many
SELECT
    COALESCE(
        NULLIF(
            utm_content,
            ''
        ),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopContentParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopContentRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopContent(ctx context.Context, arg GetTopContentParams) ([]GetTopContentRow, error) {
	rows, err := q.db.Query(ctx, getTopContent, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopContentRow
	for rows.Next() {
		var i GetTopContentRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCountries = `-- name: GetTopCountries :many
SELECT
    COALESCE(
        NULLIF(country, ''),
        'Unknown'
    ) AS name,
    COUNT(*) AS clicks
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopCountriesParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopCountriesRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopCountries(ctx context.Context, arg GetTopCountriesParams) ([]GetTopCountriesRow, error) {
	rows, err := q.db.Query(ctx, getTopCountries, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCountriesRow
	for rows.Next() {
		var i GetTopCountriesRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDevices = `-- name: GetTopDevices :many
SELECT
    device,

    COUNT(*)::BIGINT
        AS clicks
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY device
ORDER BY clicks DESC
LIMIT 10
`

type GetTopDevicesParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopDevicesRow struct {
	Device pgtype.Text
	Clicks int64
}

func (q *Queries) GetTopDevices(ctx context.Context, arg GetTopDevicesParams) ([]GetTopDevicesRow, error) {
	rows, err := q.db.Query(ctx, getTopDevices, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDevicesRow
	for rows.Next() {
		var i GetTopDevicesRow
		if err := rows.Scan(&i.Device, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMediums = `-- name: GetTopMediums :many
SELECT
    COALESCE(
        NULLIF(
            utm_medium,
            ''
        ),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopMediumsParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopMediumsRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopMediums(ctx context.Context, arg GetTopMediumsParams) ([]GetTopMediumsRow, error) {
	rows, err := q.db.Query(ctx, getTopMediums, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMediumsRow
	for rows.Next() {
		var i GetTopMediumsRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopOperatingSystems = `-- name: GetTopOperatingSystems :many
SELECT
    os AS name,
    COUNT(*)::BIGINT AS clicks
FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY os
ORDER BY clicks DESC
LIMIT 10
`

type GetTopOperatingSystemsParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopOperatingSystemsRow struct {
	Name   pgtype.Text
	Clicks int64
}

func (q *Queries) GetTopOperatingSystems(ctx context.Context, arg GetTopOperatingSystemsParams) ([]GetTopOperatingSystemsRow, error) {
	rows, err := q.db.Query(ctx, getTopOperatingSystems, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopOperatingSystemsRow
	for rows.Next() {
		var i GetTopOperatingSystemsRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReferrers = `-- name: GetTopReferrers :many
SELECT
    COALESCE(
        NULLIF(
            referrer,
            ''
        ),
        'Direct'
    )::TEXT AS source,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY source
ORDER BY clicks DESC
LIMIT 10
`

type GetTopReferrersParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopReferrersRow struct {
	Source string
	Clicks int64
}

func (q *Queries) GetTopReferrers(ctx context.Context, arg GetTopReferrersParams) ([]GetTopReferrersRow, error) {
	rows, err := q.db.Query(ctx, getTopReferrers, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopReferrersRow
	for rows.Next() {
		var i GetTopReferrersRow
		if err := rows.Scan(&i.Source, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSources = `-- name: GetTopSources :many
SELECT
    COALESCE(
        NULLIF(
            utm_source,
            ''
        ),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopSourcesParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopSourcesRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopSources(ctx context.Context, arg GetTopSourcesParams) ([]GetTopSourcesRow, error) {
	rows, err := q.db.Query(ctx, getTopSources, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSourcesRow
	for rows.Next() {
		var i GetTopSourcesRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTerms = `-- name: GetTopTerms :many
SELECT
    COALESCE(
        NULLIF(
            utm_term,
            ''
        ),
        'Unknown'
    ) AS name,

    COUNT(*)::BIGINT
        AS clicks

FROM link_analytics
WHERE link_id = $1
AND is_bot = FALSE
AND (
    $2::timestamptz IS NULL
    OR clicked_at >= $2
)
GROUP BY name
ORDER BY clicks DESC
LIMIT 10
`

type GetTopTermsParams struct {
	LinkID  pgtype.UUID
	Column2 pgtype.Timestamptz
}

type GetTopTermsRow struct {
	Name   interface{}
	Clicks int64
}

func (q *Queries) GetTopTerms(ctx context.Context, arg GetTopTermsParams) ([]GetTopTermsRow, error) {
	rows, err := q.db.Query(ctx, getTopTerms, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTermsRow
	for rows.Next() {
		var i GetTopTermsRow
		if err := rows.Scan(&i.Name, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyLinkOwnership = `-- name: VerifyLinkOwnership :one
SELECT EXISTS (
    SELECT 1
    FROM central_links
    WHERE id = $1
    AND user_id = $2
)
`

type VerifyLinkOwnershipParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) VerifyLinkOwnership(ctx context.Context, arg VerifyLinkOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyLinkOwnership, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
