// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserLinks = `-- name: CountUserLinks :one
SELECT COUNT(*)
FROM central_links
WHERE user_id = $1
AND is_deleted = FALSE
`

func (q *Queries) CountUserLinks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLinks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO central_links (
    user_id,
    title,
    slug,
    unique_id,
    target_url
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
`

type CreateLinkParams struct {
	UserID    pgtype.UUID
	Title     string
	Slug      string
	UniqueID  string
	TargetUrl string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.UniqueID,
		arg.TargetUrl,
	)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const createLinkHistory = `-- name: CreateLinkHistory :exec
INSERT INTO link_history (
    link_id,
    old_target_url,
    new_target_url
)
VALUES (
    $1, $2, $3
)
`

type CreateLinkHistoryParams struct {
	LinkID       pgtype.UUID
	OldTargetUrl string
	NewTargetUrl string
}

func (q *Queries) CreateLinkHistory(ctx context.Context, arg CreateLinkHistoryParams) error {
	_, err := q.db.Exec(ctx, createLinkHistory, arg.LinkID, arg.OldTargetUrl, arg.NewTargetUrl)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
UPDATE central_links
SET
	is_deleted = TRUE,
	deleted_at = NOW()
WHERE id = $1
AND user_id = $2
`

type DeleteLinkParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) error {
	_, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.UserID)
	return err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
FROM central_links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id pgtype.UUID) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByIDAndUserID = `-- name: GetLinkByIDAndUserID :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
FROM central_links
WHERE id = $1
AND user_id = $2
AND is_deleted = FALSE
`

type GetLinkByIDAndUserIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetLinkByIDAndUserID(ctx context.Context, arg GetLinkByIDAndUserIDParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkByIDAndUserID, arg.ID, arg.UserID)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByPublicKey = `-- name: GetLinkByPublicKey :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
FROM central_links
WHERE unique_id = $1
`

func (q *Queries) GetLinkByPublicKey(ctx context.Context, uniqueID string) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkByPublicKey, uniqueID)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
FROM central_links
WHERE user_id = $1
AND slug = $2
`

type GetLinkBySlugParams struct {
	UserID pgtype.UUID
	Slug   string
}

func (q *Queries) GetLinkBySlug(ctx context.Context, arg GetLinkBySlugParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, arg.UserID, arg.Slug)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkForRedirect = `-- name: GetLinkForRedirect :one
SELECT
    cl.id, cl.user_id, cl.title, cl.slug, cl.unique_id, cl.target_url, cl.click_count, cl.is_active, cl.created_at, cl.updated_at, cl.is_deleted, cl.deleted_at,
    u.username
FROM central_links cl
JOIN users u
ON cl.user_id = u.id
WHERE cl.unique_id = $1
AND cl.is_deleted = FALSE
AND cl.is_active = TRUE
`

type GetLinkForRedirectRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Title      string
	Slug       string
	UniqueID   string
	TargetUrl  string
	ClickCount int64
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsDeleted  pgtype.Bool
	DeletedAt  pgtype.Timestamp
	Username   string
}

func (q *Queries) GetLinkForRedirect(ctx context.Context, uniqueID string) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRow(ctx, getLinkForRedirect, uniqueID)
	var i GetLinkForRedirectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.Username,
	)
	return i, err
}

const getUserLinks = `-- name: GetUserLinks :many
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
FROM central_links
WHERE user_id = $1
AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetUserLinksParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserLinks(ctx context.Context, arg GetUserLinksParams) ([]CentralLink, error) {
	rows, err := q.db.Query(ctx, getUserLinks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CentralLink
	for rows.Next() {
		var i CentralLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.UniqueID,
			&i.TargetUrl,
			&i.ClickCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE central_links
SET click_count = click_count + 1
WHERE id = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementClickCount, id)
	return err
}

const incrementClickCountBy = `-- name: IncrementClickCountBy :exec
UPDATE central_links
SET click_count =
	click_count + $1
WHERE id =
	$2
`

type IncrementClickCountByParams struct {
	IncrementBy int64
	ID          pgtype.UUID
}

func (q *Queries) IncrementClickCountBy(ctx context.Context, arg IncrementClickCountByParams) error {
	_, err := q.db.Exec(ctx, incrementClickCountBy, arg.IncrementBy, arg.ID)
	return err
}

const toggleLinkStatus = `-- name: ToggleLinkStatus :one
UPDATE central_links
SET
    is_active = $3,
    updated_at = NOW()
WHERE id = $1
AND user_id = $2
RETURNING id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
`

type ToggleLinkStatusParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	IsActive bool
}

func (q *Queries) ToggleLinkStatus(ctx context.Context, arg ToggleLinkStatusParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, toggleLinkStatus, arg.ID, arg.UserID, arg.IsActive)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE central_links
SET
    title = $3,
    slug = $4,
    target_url = $5,
    updated_at = NOW()
WHERE id = $1
AND user_id = $2
RETURNING id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at, is_deleted, deleted_at
`

type UpdateLinkParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Slug      string
	TargetUrl string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.TargetUrl,
	)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}
