// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserLinks = `-- name: CountUserLinks :one
SELECT COUNT(*)
FROM central_links
WHERE user_id = $1
`

func (q *Queries) CountUserLinks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLinks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO central_links (
    user_id,
    title,
    slug,
    unique_id,
    target_url
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at
`

type CreateLinkParams struct {
	UserID    pgtype.UUID
	Title     string
	Slug      string
	UniqueID  string
	TargetUrl string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.UniqueID,
		arg.TargetUrl,
	)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM central_links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at
FROM central_links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id pgtype.UUID) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at
FROM central_links
WHERE user_id = $1
AND slug = $2
`

type GetLinkBySlugParams struct {
	UserID pgtype.UUID
	Slug   string
}

func (q *Queries) GetLinkBySlug(ctx context.Context, arg GetLinkBySlugParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, arg.UserID, arg.Slug)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLinks = `-- name: GetUserLinks :many
SELECT id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at
FROM central_links
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserLinks(ctx context.Context, userID pgtype.UUID) ([]CentralLink, error) {
	rows, err := q.db.Query(ctx, getUserLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CentralLink
	for rows.Next() {
		var i CentralLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.UniqueID,
			&i.TargetUrl,
			&i.ClickCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE central_links
SET
    title = $2,
    slug = $3,
    target_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, slug, unique_id, target_url, click_count, is_active, created_at, updated_at
`

type UpdateLinkParams struct {
	ID        pgtype.UUID
	Title     string
	Slug      string
	TargetUrl string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (CentralLink, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.TargetUrl,
	)
	var i CentralLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.UniqueID,
		&i.TargetUrl,
		&i.ClickCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
