// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CentralLink struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Title      string
	Slug       string
	UniqueID   string
	TargetUrl  string
	ClickCount int64
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsDeleted  pgtype.Bool
	DeletedAt  pgtype.Timestamp
}

type LinkHistory struct {
	ID           pgtype.UUID
	LinkID       pgtype.UUID
	OldTargetUrl string
	NewTargetUrl string
	ChangedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       string
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	ReplacedByToken pgtype.Text
	UserAgent       pgtype.Text
	IpAddress       pgtype.Text
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	Plan           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
