// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentIntentStatus string

const (
	PaymentIntentStatusPending   PaymentIntentStatus = "pending"
	PaymentIntentStatusSucceeded PaymentIntentStatus = "succeeded"
	PaymentIntentStatusFailed    PaymentIntentStatus = "failed"
	PaymentIntentStatusCancelled PaymentIntentStatus = "cancelled"
	PaymentIntentStatusExpired   PaymentIntentStatus = "expired"
)

func (e *PaymentIntentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentIntentStatus(s)
	case string:
		*e = PaymentIntentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentIntentStatus: %T", src)
	}
	return nil
}

type NullPaymentIntentStatus struct {
	PaymentIntentStatus PaymentIntentStatus
	Valid               bool // Valid is true if PaymentIntentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentIntentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentIntentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentIntentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentIntentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentIntentStatus), nil
}

type PaymentProvider string

const (
	PaymentProviderDodo PaymentProvider = "dodo"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider
	Valid           bool // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type SubscriptionPlan string

const (
	SubscriptionPlanFree    SubscriptionPlan = "free"
	SubscriptionPlanStarter SubscriptionPlan = "starter"
	SubscriptionPlanPro     SubscriptionPlan = "pro"
)

func (e *SubscriptionPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionPlan(s)
	case string:
		*e = SubscriptionPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionPlan: %T", src)
	}
	return nil
}

type NullSubscriptionPlan struct {
	SubscriptionPlan SubscriptionPlan
	Valid            bool // Valid is true if SubscriptionPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionPlan) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionPlan), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusInactive  SubscriptionStatus = "inactive"
	SubscriptionStatusPastDue   SubscriptionStatus = "past_due"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type WebhookProcessingStatus string

const (
	WebhookProcessingStatusPending    WebhookProcessingStatus = "pending"
	WebhookProcessingStatusProcessing WebhookProcessingStatus = "processing"
	WebhookProcessingStatusProcessed  WebhookProcessingStatus = "processed"
	WebhookProcessingStatusFailed     WebhookProcessingStatus = "failed"
)

func (e *WebhookProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookProcessingStatus(s)
	case string:
		*e = WebhookProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookProcessingStatus: %T", src)
	}
	return nil
}

type NullWebhookProcessingStatus struct {
	WebhookProcessingStatus WebhookProcessingStatus
	Valid                   bool // Valid is true if WebhookProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookProcessingStatus), nil
}

type CentralLink struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Title      string
	Slug       string
	UniqueID   string
	TargetUrl  string
	ClickCount int64
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsDeleted  pgtype.Bool
	DeletedAt  pgtype.Timestamptz
}

type LinkAnalytic struct {
	ID          pgtype.UUID
	LinkID      pgtype.UUID
	Referrer    pgtype.Text
	Country     pgtype.Text
	City        pgtype.Text
	Browser     pgtype.Text
	Os          pgtype.Text
	Device      pgtype.Text
	IpAddress   *netip.Addr
	ClickedAt   pgtype.Timestamptz
	UtmSource   pgtype.Text
	UtmMedium   pgtype.Text
	UtmCampaign pgtype.Text
	UtmTerm     pgtype.Text
	UtmContent  pgtype.Text
	IsBot       bool
}

type LinkHistory struct {
	ID           pgtype.UUID
	LinkID       pgtype.UUID
	OldTargetUrl string
	NewTargetUrl string
	ChangedAt    pgtype.Timestamptz
}

type PaymentIntent struct {
	ID              pgtype.UUID
	ProviderEventID string
	Provider        PaymentProvider
	EventType       string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	UserID          pgtype.UUID
	Plan            NullSubscriptionPlan
	IdempotencyKey  pgtype.Text
	Status          PaymentIntentStatus
}

type PaymentWebhook struct {
	ID                  pgtype.UUID
	Provider            PaymentProvider
	ProviderEventID     string
	EventType           string
	Headers             []byte
	Payload             []byte
	ProcessingStatus    WebhookProcessingStatus
	ProcessingAttempts  int32
	LastError           pgtype.Text
	ReceivedAt          pgtype.Timestamptz
	ProcessedAt         pgtype.Timestamptz
	ProcessingStartedAt pgtype.Timestamptz
	NextRetryAt         pgtype.Timestamptz
}

type RefreshToken struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TokenHash       string
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	ReplacedByToken pgtype.Text
	UserAgent       pgtype.Text
	IpAddress       pgtype.Text
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserSubscription struct {
	ID                     pgtype.UUID
	UserID                 pgtype.UUID
	Plan                   SubscriptionPlan
	Status                 SubscriptionStatus
	ProviderCustomerID     pgtype.Text
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CancelAtPeriodEnd      bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}
