// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentWebhook = `-- name: CreatePaymentWebhook :exec
INSERT INTO payment_webhooks (
    provider,
    provider_event_id,
    event_type,
    headers,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (provider, provider_event_id)
DO NOTHING
`

type CreatePaymentWebhookParams struct {
	Provider        PaymentProvider
	ProviderEventID string
	EventType       string
	Headers         []byte
	Payload         []byte
}

// Duplicate provider events are ignored.
// Idempotency is enforced by the UNIQUE(provider, provider_event_id) constraint.
func (q *Queries) CreatePaymentWebhook(ctx context.Context, arg CreatePaymentWebhookParams) error {
	_, err := q.db.Exec(ctx, createPaymentWebhook,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.Headers,
		arg.Payload,
	)
	return err
}

const getPaymentWebhook = `-- name: GetPaymentWebhook :one
SELECT id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at
FROM payment_webhooks
WHERE
    provider = $1
    AND provider_event_id = $2
LIMIT 1
FOR UPDATE
`

type GetPaymentWebhookParams struct {
	Provider        PaymentProvider
	ProviderEventID string
}

func (q *Queries) GetPaymentWebhook(ctx context.Context, arg GetPaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, getPaymentWebhook, arg.Provider, arg.ProviderEventID)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPaymentWebhookFailed = `-- name: MarkPaymentWebhookFailed :one
UPDATE payment_webhooks
SET
    processing_status = 'failed',
    last_error = $2,
    processed_at = NOW()
WHERE id = $1
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at
`

type MarkPaymentWebhookFailedParams struct {
	ID        pgtype.UUID
	LastError pgtype.Text
}

func (q *Queries) MarkPaymentWebhookFailed(ctx context.Context, arg MarkPaymentWebhookFailedParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookFailed, arg.ID, arg.LastError)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPaymentWebhookProcessed = `-- name: MarkPaymentWebhookProcessed :one
UPDATE payment_webhooks
SET
    processing_status = 'processed',
    processed_at = NOW(),
    last_error = NULL
WHERE id = $1
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at
`

func (q *Queries) MarkPaymentWebhookProcessed(ctx context.Context, id pgtype.UUID) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookProcessed, id)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPaymentWebhookProcessing = `-- name: MarkPaymentWebhookProcessing :one
UPDATE payment_webhooks
SET
    processing_status = 'processing',
    processing_attempts =
        processing_attempts + 1,
    processed_at = NULL,
    last_error = NULL
WHERE 
    id = $1
    AND processing_status = 'pending'
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at
`

func (q *Queries) MarkPaymentWebhookProcessing(ctx context.Context, id pgtype.UUID) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookProcessing, id)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
