// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPaymentWebhook = `-- name: ClaimNextPaymentWebhook :one
WITH next_webhook AS (
    SELECT pw.id
    FROM payment_webhooks AS pw
    WHERE
        pw.processing_status = 'pending'

        OR (
            pw.processing_status = 'failed'
            AND pw.next_retry_at IS NOT NULL
            AND pw.next_retry_at <= NOW()
            AND pw.processing_attempts < $1
        )

        OR (
            pw.processing_status = 'processing'
            AND pw.processing_started_at IS NOT NULL
            AND pw.processing_started_at <=
                NOW() - (
                    $2
                    * INTERVAL '1 second'
                )
            AND pw.processing_attempts < $1
        )

    ORDER BY
        CASE
            WHEN pw.processing_status = 'pending'
                THEN 0
            WHEN pw.processing_status = 'failed'
                THEN 1
            WHEN pw.processing_status = 'processing'
                THEN 2
            ELSE 3
        END,

        COALESCE(
            pw.next_retry_at,
            pw.processing_started_at,
            pw.received_at
        ),

        pw.received_at

    FOR UPDATE OF pw
    SKIP LOCKED

    LIMIT 1
)

UPDATE payment_webhooks AS pw
SET
    processing_status = 'processing',

    processing_attempts =
        pw.processing_attempts + 1,

    processing_started_at =
        NOW(),

    next_retry_at =
        NULL

FROM next_webhook AS nw

WHERE pw.id = nw.id

RETURNING pw.id, pw.provider, pw.provider_event_id, pw.event_type, pw.headers, pw.payload, pw.processing_status, pw.processing_attempts, pw.last_error, pw.received_at, pw.processed_at, pw.processing_started_at, pw.next_retry_at
`

type ClaimNextPaymentWebhookParams struct {
	MaxAttempts         int32
	StaleTimeoutSeconds interface{}
}

func (q *Queries) ClaimNextPaymentWebhook(ctx context.Context, arg ClaimNextPaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, claimNextPaymentWebhook, arg.MaxAttempts, arg.StaleTimeoutSeconds)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.ProcessingStartedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const createPaymentWebhook = `-- name: CreatePaymentWebhook :exec
INSERT INTO payment_webhooks (
    provider,
    provider_event_id,
    event_type,
    headers,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (provider, provider_event_id)
DO NOTHING
`

type CreatePaymentWebhookParams struct {
	Provider        PaymentProvider
	ProviderEventID string
	EventType       string
	Headers         []byte
	Payload         []byte
}

// Duplicate provider events are ignored.
// Idempotency is enforced by the UNIQUE(provider, provider_event_id) constraint.
func (q *Queries) CreatePaymentWebhook(ctx context.Context, arg CreatePaymentWebhookParams) error {
	_, err := q.db.Exec(ctx, createPaymentWebhook,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.Headers,
		arg.Payload,
	)
	return err
}

const failExhaustedStalePaymentWebhooks = `-- name: FailExhaustedStalePaymentWebhooks :execrows
UPDATE payment_webhooks
SET
    processing_status = 'failed',
    processing_started_at = NULL,
    next_retry_at = NULL,
    processed_at = NULL,
    last_error =
        'payment webhook processing exceeded maximum attempts after worker interruption'
WHERE
    processing_status = 'processing'
    AND processing_started_at IS NOT NULL
    AND processing_started_at <=
        NOW() - (
            $1
            * INTERVAL '1 second'
        )
    AND processing_attempts >=
        $2
`

type FailExhaustedStalePaymentWebhooksParams struct {
	StaleTimeoutSeconds interface{}
	MaxAttempts         int32
}

func (q *Queries) FailExhaustedStalePaymentWebhooks(ctx context.Context, arg FailExhaustedStalePaymentWebhooksParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExhaustedStalePaymentWebhooks, arg.StaleTimeoutSeconds, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaymentWebhook = `-- name: GetPaymentWebhook :one
SELECT id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at, processing_started_at, next_retry_at
FROM payment_webhooks
WHERE
    provider = $1
    AND provider_event_id = $2
LIMIT 1
FOR UPDATE
`

type GetPaymentWebhookParams struct {
	Provider        PaymentProvider
	ProviderEventID string
}

func (q *Queries) GetPaymentWebhook(ctx context.Context, arg GetPaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, getPaymentWebhook, arg.Provider, arg.ProviderEventID)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.ProcessingStartedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const markPaymentWebhookFailed = `-- name: MarkPaymentWebhookFailed :one
UPDATE payment_webhooks
SET
    processing_status = 'failed',
    last_error = $2,
    processed_at = NULL,
    processing_started_at = NULL,
    next_retry_at = $3
WHERE id = $1
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at, processing_started_at, next_retry_at
`

type MarkPaymentWebhookFailedParams struct {
	ID          pgtype.UUID
	LastError   pgtype.Text
	NextRetryAt pgtype.Timestamptz
}

func (q *Queries) MarkPaymentWebhookFailed(ctx context.Context, arg MarkPaymentWebhookFailedParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookFailed, arg.ID, arg.LastError, arg.NextRetryAt)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.ProcessingStartedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const markPaymentWebhookProcessed = `-- name: MarkPaymentWebhookProcessed :one
UPDATE payment_webhooks
SET
    processing_status = 'processed',
    processed_at = NOW(),
    processing_started_at = NULL,
    next_retry_at = NULL,
    last_error = NULL
WHERE id = $1
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at, processing_started_at, next_retry_at
`

func (q *Queries) MarkPaymentWebhookProcessed(ctx context.Context, id pgtype.UUID) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookProcessed, id)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.ProcessingStartedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const markPaymentWebhookProcessing = `-- name: MarkPaymentWebhookProcessing :one
UPDATE payment_webhooks
SET
    processing_status = 'processing',
    processing_attempts =
        processing_attempts + 1,
    processed_at = NULL,
    last_error = NULL
WHERE 
    id = $1
    AND processing_status = 'pending'
RETURNING id, provider, provider_event_id, event_type, headers, payload, processing_status, processing_attempts, last_error, received_at, processed_at, processing_started_at, next_retry_at
`

func (q *Queries) MarkPaymentWebhookProcessing(ctx context.Context, id pgtype.UUID) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, markPaymentWebhookProcessing, id)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ProcessingStatus,
		&i.ProcessingAttempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.ProcessingStartedAt,
		&i.NextRetryAt,
	)
	return i, err
}
