// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUserSubscriptionPlan = `-- name: ActivateUserSubscriptionPlan :one
UPDATE user_subscriptions
SET
    plan = $2,
    status = 'active',
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type ActivateUserSubscriptionPlanParams struct {
	UserID pgtype.UUID
	Plan   SubscriptionPlan
}

func (q *Queries) ActivateUserSubscriptionPlan(ctx context.Context, arg ActivateUserSubscriptionPlanParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, activateUserSubscriptionPlan, arg.UserID, arg.Plan)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserLinksForSubscription = `-- name: CountUserLinksForSubscription :one
SELECT COUNT(*)
FROM central_links
WHERE user_id = $1
AND is_deleted = FALSE
`

func (q *Queries) CountUserLinksForSubscription(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLinksForSubscription, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (
    provider_event_id,
    provider,
    event_type,
    user_id,
    plan,
    idempotency_key,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'pending'
)
RETURNING id, provider_event_id, provider, event_type, payload, created_at, user_id, plan, idempotency_key, status
`

type CreatePaymentIntentParams struct {
	ProviderEventID string
	Provider        PaymentProvider
	EventType       string
	UserID          pgtype.UUID
	Plan            NullSubscriptionPlan
	IdempotencyKey  pgtype.Text
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.ProviderEventID,
		arg.Provider,
		arg.EventType,
		arg.UserID,
		arg.Plan,
		arg.IdempotencyKey,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
		&i.Status,
	)
	return i, err
}

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO user_subscriptions (
    user_id,
    plan,
    status
)
VALUES (
    $1,
    'free',
    'active'
)
ON CONFLICT (user_id)
DO UPDATE
SET updated_at = NOW()
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

func (q *Queries) CreateUserSubscription(ctx context.Context, userID pgtype.UUID) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, createUserSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentIntentForUpdate = `-- name: GetPaymentIntentForUpdate :one
SELECT id, provider_event_id, provider, event_type, payload, created_at, user_id, plan, idempotency_key, status
FROM payment_intents
WHERE
    provider = $1
    AND provider_event_id = $2
LIMIT 1
FOR UPDATE
`

type GetPaymentIntentForUpdateParams struct {
	Provider        PaymentProvider
	ProviderEventID string
}

func (q *Queries) GetPaymentIntentForUpdate(ctx context.Context, arg GetPaymentIntentForUpdateParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentForUpdate, arg.Provider, arg.ProviderEventID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
		&i.Status,
	)
	return i, err
}

const getUserPaymentIntentByCheckoutID = `-- name: GetUserPaymentIntentByCheckoutID :one
SELECT id, provider_event_id, provider, event_type, payload, created_at, user_id, plan, idempotency_key, status
FROM payment_intents
WHERE
    provider = $1
    AND provider_event_id = $2
    AND user_id = $3
LIMIT 1
`

type GetUserPaymentIntentByCheckoutIDParams struct {
	Provider        PaymentProvider
	ProviderEventID string
	UserID          pgtype.UUID
}

func (q *Queries) GetUserPaymentIntentByCheckoutID(ctx context.Context, arg GetUserPaymentIntentByCheckoutIDParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getUserPaymentIntentByCheckoutID, arg.Provider, arg.ProviderEventID, arg.UserID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
		&i.Status,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
FROM user_subscriptions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID pgtype.UUID) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentIntentFailedByID = `-- name: MarkPaymentIntentFailedByID :one
UPDATE payment_intents
SET status = 'failed'
WHERE
    id = $1
    AND status = 'pending'
RETURNING id, provider_event_id, provider, event_type, payload, created_at, user_id, plan, idempotency_key, status
`

func (q *Queries) MarkPaymentIntentFailedByID(ctx context.Context, id pgtype.UUID) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, markPaymentIntentFailedByID, id)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
		&i.Status,
	)
	return i, err
}

const markPaymentIntentSucceededByID = `-- name: MarkPaymentIntentSucceededByID :one
UPDATE payment_intents
SET
    status = 'succeeded'
WHERE
    id = $1
    AND status = 'pending'
RETURNING id, provider_event_id, provider, event_type, payload, created_at, user_id, plan, idempotency_key, status
`

func (q *Queries) MarkPaymentIntentSucceededByID(ctx context.Context, id pgtype.UUID) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, markPaymentIntentSucceededByID, id)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
		&i.Status,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE user_subscriptions
SET
    plan = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpdateUserPlanParams struct {
	UserID pgtype.UUID
	Plan   SubscriptionPlan
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, updateUserPlan, arg.UserID, arg.Plan)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE user_subscriptions
SET
    plan =
        COALESCE($2, plan),

    status =
        COALESCE($3, status),

    provider_customer_id =
        COALESCE(
            $4,
            provider_customer_id
        ),

    provider_subscription_id =
        COALESCE(
            $5,
            provider_subscription_id
        ),

    current_period_start =
        COALESCE(
            $6,
            current_period_start
        ),

    current_period_end =
        COALESCE(
            $7,
            current_period_end
        ),

    cancel_at_period_end =
        COALESCE(
            $8,
            cancel_at_period_end
        ),

    updated_at = NOW()

WHERE user_id = $1
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpdateUserSubscriptionParams struct {
	UserID                 pgtype.UUID
	Plan                   SubscriptionPlan
	Status                 SubscriptionStatus
	ProviderCustomerID     pgtype.Text
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CancelAtPeriodEnd      bool
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, updateUserSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSubscription = `-- name: UpsertUserSubscription :one
INSERT INTO user_subscriptions (
    user_id,
    plan,
    status,
    provider_customer_id,
    provider_subscription_id,
    current_period_start,
    current_period_end,
    cancel_at_period_end
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (user_id)
DO UPDATE
SET
    plan = EXCLUDED.plan,
    status = EXCLUDED.status,
    provider_customer_id =
        EXCLUDED.provider_customer_id,
    provider_subscription_id =
        EXCLUDED.provider_subscription_id,
    current_period_start =
        EXCLUDED.current_period_start,
    current_period_end =
        EXCLUDED.current_period_end,
    cancel_at_period_end =
        EXCLUDED.cancel_at_period_end,
    updated_at = NOW()
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpsertUserSubscriptionParams struct {
	UserID                 pgtype.UUID
	Plan                   SubscriptionPlan
	Status                 SubscriptionStatus
	ProviderCustomerID     pgtype.Text
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CancelAtPeriodEnd      bool
}

func (q *Queries) UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, upsertUserSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
