// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserLinksForSubscription = `-- name: CountUserLinksForSubscription :one
SELECT COUNT(*)
FROM central_links
WHERE user_id = $1
AND is_deleted = FALSE
`

func (q *Queries) CountUserLinksForSubscription(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLinksForSubscription, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_events (
    provider_event_id,
    provider_name,
    event_type,
    user_id,
    plan,
    idempotency_key,
    processed
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    FALSE
)
RETURNING id, provider_event_id, provider_name, event_type, processed, payload, created_at, user_id, plan, idempotency_key
`

type CreatePaymentIntentParams struct {
	ProviderEventID string
	ProviderName    string
	EventType       string
	UserID          pgtype.UUID
	Plan            pgtype.Text
	IdempotencyKey  pgtype.Text
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.ProviderEventID,
		arg.ProviderName,
		arg.EventType,
		arg.UserID,
		arg.Plan,
		arg.IdempotencyKey,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.ProviderName,
		&i.EventType,
		&i.Processed,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
	)
	return i, err
}

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO user_subscriptions (
    user_id,
    plan,
    status
)
VALUES (
    $1,
    'free',
    'active'
)
ON CONFLICT (user_id)
DO UPDATE
SET updated_at = NOW()
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

func (q *Queries) CreateUserSubscription(ctx context.Context, userID pgtype.UUID) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, createUserSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentIntentByIdempotency = `-- name: GetPaymentIntentByIdempotency :one
SELECT id, provider_event_id, provider_name, event_type, processed, payload, created_at, user_id, plan, idempotency_key
FROM payment_events
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetPaymentIntentByIdempotency(ctx context.Context, idempotencyKey pgtype.Text) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIdempotency, idempotencyKey)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.ProviderName,
		&i.EventType,
		&i.Processed,
		&i.Payload,
		&i.CreatedAt,
		&i.UserID,
		&i.Plan,
		&i.IdempotencyKey,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
FROM user_subscriptions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID pgtype.UUID) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentProcessed = `-- name: MarkPaymentProcessed :exec
UPDATE payment_events
SET
    processed = TRUE,
    updated_at = NOW()
WHERE provider_event_id = $1
`

func (q *Queries) MarkPaymentProcessed(ctx context.Context, providerEventID string) error {
	_, err := q.db.Exec(ctx, markPaymentProcessed, providerEventID)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE user_subscriptions
SET
    plan =
        COALESCE($2, plan),

    status =
        COALESCE($3, status),

    provider_customer_id =
        COALESCE(
            $4,
            provider_customer_id
        ),

    provider_subscription_id =
        COALESCE(
            $5,
            provider_subscription_id
        ),

    current_period_start =
        COALESCE(
            $6,
            current_period_start
        ),

    current_period_end =
        COALESCE(
            $7,
            current_period_end
        ),

    cancel_at_period_end =
        COALESCE(
            $8,
            cancel_at_period_end
        ),

    updated_at = NOW()

WHERE user_id = $1
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpdateUserSubscriptionParams struct {
	UserID                 pgtype.UUID
	Plan                   SubscriptionPlan
	Status                 SubscriptionStatus
	ProviderCustomerID     pgtype.Text
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CancelAtPeriodEnd      bool
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, updateUserSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSubscription = `-- name: UpsertUserSubscription :one
INSERT INTO user_subscriptions (
    user_id,
    plan,
    status,
    provider_customer_id,
    provider_subscription_id,
    current_period_start,
    current_period_end,
    cancel_at_period_end
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (user_id)
DO UPDATE
SET
    plan = EXCLUDED.plan,
    status = EXCLUDED.status,
    provider_customer_id =
        EXCLUDED.provider_customer_id,
    provider_subscription_id =
        EXCLUDED.provider_subscription_id,
    current_period_start =
        EXCLUDED.current_period_start,
    current_period_end =
        EXCLUDED.current_period_end,
    cancel_at_period_end =
        EXCLUDED.cancel_at_period_end,
    updated_at = NOW()
RETURNING id, user_id, plan, status, provider_customer_id, provider_subscription_id, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpsertUserSubscriptionParams struct {
	UserID                 pgtype.UUID
	Plan                   SubscriptionPlan
	Status                 SubscriptionStatus
	ProviderCustomerID     pgtype.Text
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CancelAtPeriodEnd      bool
}

func (q *Queries) UpsertUserSubscription(ctx context.Context, arg UpsertUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, upsertUserSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
