// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    password_hash,
    google_id,
    profile_picture
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id,
    email,
    username,
    password_hash,
    google_id,
    profile_picture,
    email_verified,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
}

type CreateUserRow struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	EmailVerified  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.GoogleID,
		arg.ProfilePicture,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
    email,
    username,
    password_hash,
    google_id,
    profile_picture,
    email_verified,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	EmailVerified  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id,
    email,
    username,
    password_hash,
    google_id,
    profile_picture,
    email_verified,
    created_at,
    updated_at
FROM users
WHERE google_id = $1
`

type GetUserByGoogleIDRow struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	EmailVerified  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (GetUserByGoogleIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i GetUserByGoogleIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
    email,
    username,
    password_hash,
    google_id,
    profile_picture,
    email_verified,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	EmailVerified  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id,
    email,
    username,
    password_hash,
    google_id,
    profile_picture,
    email_verified,
    created_at,
    updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             pgtype.UUID
	Email          string
	Username       string
	PasswordHash   pgtype.Text
	GoogleID       pgtype.Text
	ProfilePicture pgtype.Text
	EmailVerified  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
